// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace W5i___Controle_de_Atendimentos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501165700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("W5i___Controle_de_Atendimentos.Entities.Chamado", b =>
                {
                    b.Property<int>("chamadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("chamadoID"));

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("descricao")
                        .HasColumnType("text");

                    b.Property<int>("prioridadeID")
                        .HasColumnType("integer");

                    b.Property<int>("setorID")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("chamadoID");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("W5i___Controle_de_Atendimentos.Entities.Prioridade", b =>
                {
                    b.Property<int>("prioridadeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("prioridadeID"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("tempoEstimadoHoras")
                        .HasColumnType("integer");

                    b.HasKey("prioridadeID");

                    b.ToTable("Prioridades");
                });

            modelBuilder.Entity("W5i___Controle_de_Atendimentos.Entities.Setor", b =>
                {
                    b.Property<int>("setorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("setorID"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("setorID");

                    b.ToTable("Setores");
                });
#pragma warning restore 612, 618
        }
    }
}
